theme: jekyll-theme-minimal
title: [Characterization for Genes across Species]
description: [Code supporting the paper "A Comparative Analysis of Matrix Metalloproteinase Genes Across Marine and Terrestrial Mammals Implications for Wound Repair" by Iris Milligan et al. 2026]